export const deviceBrands = [
  { id: 'apple', name: 'Apple' },
  { id: 'samsung', name: 'Samsung' },
  { id: 'oppo', name: 'Oppo' },
  { id: 'vivo', name: 'Vivo' },
  { id: 'redmi', name: 'Redmi' },
  { id: 'realme', name: 'Realme' },
  { id: 'tecno', name: 'Tecno' },
  { id: 'iqoo', name: 'iQOO' },
  { id: 'oneplus', name: 'OnePlus' },
  { id: 'google_pixel', name: 'Google Pixel' },
  { id: 'other', name: 'Other' },
];

export const deviceModels: { [key: string]: { id: string; name: string }[] } = {
  apple: [
    { id: 'iphone_15_pro_max', name: 'iPhone 15 Pro Max' },
    { id: 'iphone_15_pro', name: 'iPhone 15 Pro' },
    { id: 'iphone_15_plus', name: 'iPhone 15 Plus' },
    { id: 'iphone_15', name: 'iPhone 15' },
    { id: 'iphone_14_pro_max', name: 'iPhone 14 Pro Max' },
    { id: 'iphone_14_pro', name: 'iPhone 14 Pro' },
    { id: 'iphone_14_plus', name: 'iPhone 14 Plus' },
    { id: 'iphone_14', name: 'iPhone 14' },
    { id: 'iphone_13_pro_max', name: 'iPhone 13 Pro Max' },
    { id: 'iphone_13_pro', name: 'iPhone 13 Pro' },
    { id: 'iphone_13', name: 'iPhone 13' },
    { id: 'iphone_13_mini', name: 'iPhone 13 Mini' },
    { id: 'iphone_12_pro_max', name: 'iPhone 12 Pro Max' },
    { id: 'iphone_12_pro', name: 'iPhone 12 Pro' },
    { id: 'iphone_12', name: 'iPhone 12' },
    { id: 'iphone_12_mini', name: 'iPhone 12 Mini' },
    { id: 'iphone_se_2022', name: 'iPhone SE (2022)' },
    { id: 'iphone_11_pro_max', name: 'iPhone 11 Pro Max' },
    { id: 'iphone_11_pro', name: 'iPhone 11 Pro' },
    { id: 'iphone_11', name: 'iPhone 11' },
    { id: 'iphone_se_2020', name: 'iPhone SE (2020)' },
    { id: 'iphone_xs_max', name: 'iPhone XS Max' },
    { id: 'iphone_xs', name: 'iPhone XS' },
    { id: 'iphone_xr', name: 'iPhone XR' },
    { id: 'iphone_x', name: 'iPhone X' },
    { id: 'iphone_8_plus', name: 'iPhone 8 Plus' },
    { id: 'iphone_8', name: 'iPhone 8' },
    { id: 'iphone_7_plus', name: 'iPhone 7 Plus' },
    { id: 'iphone_7', name: 'iPhone 7' },
  ],
  samsung: [
    { id: 'galaxy_s24_ultra', name: 'Galaxy S24 Ultra' },
    { id: 'galaxy_s24_plus', name: 'Galaxy S24+' },
    { id: 'galaxy_s24', name: 'Galaxy S24' },
    { id: 'galaxy_s23_ultra', name: 'Galaxy S23 Ultra' },
    { id: 'galaxy_s23_plus', name: 'Galaxy S23+' },
    { id: 'galaxy_s23', name: 'Galaxy S23' },
    { id: 'galaxy_s23_fe', name: 'Galaxy S23 FE' },
    { id: 'galaxy_z_fold5', name: 'Galaxy Z Fold5' },
    { id: 'galaxy_z_flip5', name: 'Galaxy Z Flip5' },
    { id: 'galaxy_z_fold4', name: 'Galaxy Z Fold4' },
    { id: 'galaxy_z_flip4', name: 'Galaxy Z Flip4' },
    { id: 'galaxy_a55', name: 'Galaxy A55' },
    { id: 'galaxy_a35', name: 'Galaxy A35' },
    { id: 'galaxy_a15', name: 'Galaxy A15' },
    { id: 'galaxy_m55', name: 'Galaxy M55' },
    { id: 'galaxy_m34', name: 'Galaxy M34' },
    { id: 'galaxy_f54', name: 'Galaxy F54' },
  ],
  oppo: [
      { id: 'reno_11_pro', name: 'Reno 11 Pro' },
      { id: 'reno_11', name: 'Reno 11' },
      { id: 'find_n3_flip', name: 'Find N3 Flip' },
      { id: 'f25_pro', name: 'F25 Pro' },
      { id: 'a79', name: 'A79' },
      { id: 'a59', name: 'A59' },
      { id: 'reno_10_pro_plus', name: 'Reno 10 Pro+' },
      { id: 'reno_10_pro', name: 'Reno 10 Pro' },
      { id: 'reno_10', name: 'Reno 10' },
  ],
  vivo: [
      { id: 'v30_pro', name: 'V30 Pro' },
      { id: 'v30', name: 'V30' },
      { id: 'x100_pro', name: 'X100 Pro' },
      { id: 'x100', name: 'X100' },
      { id: 't3', name: 'T3' },
      { id: 't2_pro', name: 'T2 Pro' },
      { id: 'y200e', name: 'Y200e' },
      { id: 'y28', name: 'Y28' },
  ],
  redmi: [
      { id: 'note_13_pro_plus', name: 'Note 13 Pro+' },
      { id: 'note_13_pro', name: 'Note 13 Pro' },
      { id: 'note_13', name: 'Note 13' },
      { id: '13c', name: '13C' },
      { id: '12', name: '12' },
      { id: 'note_12_pro_plus', name: 'Note 12 Pro+' },
      { id: 'note_12_pro', name: 'Note 12 Pro' },
      { id: 'note_12', name: 'Note 12' },
  ],
  realme: [
      { id: '12_pro_plus', name: '12 Pro+' },
      { id: '12_pro', name: '12 Pro' },
      { id: '12_plus', name: '12+' },
      { id: 'narzo_70_pro', name: 'Narzo 70 Pro' },
      { id: 'narzo_60_pro', name: 'Narzo 60 Pro' },
      { id: 'p1', name: 'P1' },
      { id: 'c67', name: 'C67' },
  ],
  tecno: [
      { id: 'pova_6_pro', name: 'Pova 6 Pro' },
      { id: 'spark_20c', name: 'Spark 20C' },
      { id: 'spark_20', name: 'Spark 20' },
      { id: 'phantom_v_fold', name: 'Phantom V Fold' },
      { id: 'phantom_v_flip', name: 'Phantom V Flip' },
      { id: 'camon_30_premier', name: 'Camon 30 Premier' },
  ],
  iqoo: [
      { id: '12', name: '12' },
      { id: 'neo_9_pro', name: 'Neo 9 Pro' },
      { id: 'z9', name: 'Z9' },
      { id: 'z9x', name: 'Z9x' },
      { id: 'neo_7_pro', name: 'Neo 7 Pro' },
      { id: 'z7_pro', name: 'Z7 Pro' },
  ],
  oneplus: [
    { id: 'oneplus_12', name: 'OnePlus 12' },
    { id: 'oneplus_12r', name: 'OnePlus 12R' },
    { id: 'oneplus_11', name: 'OnePlus 11' },
    { id: 'oneplus_11r', name: 'OnePlus 11R' },
    { id: 'oneplus_nord_ce4', name: 'OnePlus Nord CE 4' },
    { id: 'oneplus_nord_3', name: 'OnePlus Nord 3' },
    { id: 'oneplus_open', name: 'OnePlus Open' },
  ],
  google_pixel: [
      { id: 'pixel_8_pro', name: 'Pixel 8 Pro' },
      { id: 'pixel_8', name: 'Pixel 8' },
      { id: 'pixel_8a', name: 'Pixel 8a' },
      { id: 'pixel_fold', name: 'Pixel Fold' },
      { id: 'pixel_7_pro', name: 'Pixel 7 Pro' },
      { id: 'pixel_7', name: 'Pixel 7' },
      { id: 'pixel_7a', name: 'Pixel 7a' },
      { id: 'pixel_6_pro', name: 'Pixel 6 Pro' },
      { id: 'pixel_6', name: 'Pixel 6' },
      { id: 'pixel_6a', name: 'Pixel 6a' },
  ],
  other: [],
};
