export const deviceBrands = [
  { id: 'apple', name: 'Apple' },
  { id: 'samsung', name: 'Samsung' },
  { id: 'oppo', name: 'Oppo' },
  { id: 'vivo', name: 'Vivo' },
  { id: 'redmi', name: 'Redmi' },
  { id: 'realme', name: 'Realme' },
  { id: 'tecno', name: 'Tecno' },
  { id: 'iqoo', name: 'iQOO' },
  { id: 'oneplus', name: 'OnePlus' },
  { id: 'google_pixel', name: 'Google Pixel' },
  { id: 'other', name: 'Other' },
];

export const deviceModels: { [key: string]: { id: string; name: string }[] } = {
  apple: [
    { id: 'iphone_15_pro_max', name: 'iPhone 15 Pro Max' },
    { id: 'iphone_15_pro', name: 'iPhone 15 Pro' },
    { id: 'iphone_15_plus', name: 'iPhone 15 Plus' },
    { id: 'iphone_15', name: 'iPhone 15' },
    { id: 'iphone_14_pro_max', name: 'iPhone 14 Pro Max' },
    { id: 'iphone_14_pro', name: 'iPhone 14 Pro' },
    { id: 'iphone_14_plus', name: 'iPhone 14 Plus' },
    { id: 'iphone_14', name: 'iPhone 14' },
    { id: 'iphone_13_pro_max', name: 'iPhone 13 Pro Max' },
    { id: 'iphone_13_pro', name: 'iPhone 13 Pro' },
    { id: 'iphone_13', name: 'iPhone 13' },
    { id: 'iphone_13_mini', name: 'iPhone 13 Mini' },
    { id: 'iphone_12_pro_max', name: 'iPhone 12 Pro Max' },
    { id: 'iphone_12_pro', name: 'iPhone 12 Pro' },
    { id: 'iphone_12', name: 'iPhone 12' },
    { id: 'iphone_12_mini', name: 'iPhone 12 Mini' },
    { id: 'iphone_se_2022', name: 'iPhone SE (2022)' },
    { id: 'iphone_11_pro_max', name: 'iPhone 11 Pro Max' },
    { id: 'iphone_11_pro', name: 'iPhone 11 Pro' },
    { id: 'iphone_11', name: 'iPhone 11' },
    { id: 'iphone_se_2020', name: 'iPhone SE (2020)' },
    { id: 'iphone_xs_max', name: 'iPhone XS Max' },
    { id: 'iphone_xs', name: 'iPhone XS' },
    { id: 'iphone_xr', name: 'iPhone XR' },
    { id: 'iphone_x', name: 'iPhone X' },
    { id: 'iphone_8_plus', name: 'iPhone 8 Plus' },
    { id: 'iphone_8', name: 'iPhone 8' },
    { id: 'iphone_7_plus', name: 'iPhone 7 Plus' },
    { id: 'iphone_7', name: 'iPhone 7' },
  ],
  samsung: [
    { id: 'galaxy_s24_ultra', name: 'Galaxy S24 Ultra' },
    { id: 'galaxy_s24_plus', name: 'Galaxy S24+' },
    { id: 'galaxy_s24', name: 'Galaxy S24' },
    { id: 'galaxy_s23_ultra', name: 'Galaxy S23 Ultra' },
    { id: 'galaxy_s23_plus', name: 'Galaxy S23+' },
    { id: 'galaxy_s23', name: 'Galaxy S23' },
    { id: 'galaxy_s23_fe', name: 'Galaxy S23 FE' },
    { id: 'galaxy_s22_ultra', name: 'Galaxy S22 Ultra' },
    { id: 'galaxy_s22_plus', name: 'Galaxy S22+' },
    { id: 'galaxy_s22', name: 'Galaxy S22' },
    { id: 'galaxy_s21_ultra', name: 'Galaxy S21 Ultra' },
    { id: 'galaxy_s21_plus', name: 'Galaxy S21+' },
    { id: 'galaxy_s21', name: 'Galaxy S21' },
    { id: 'galaxy_s21_fe', name: 'Galaxy S21 FE' },
    { id: 'galaxy_s20_ultra', name: 'Galaxy S20 Ultra' },
    { id: 'galaxy_s20_plus', name: 'Galaxy S20+' },
    { id: 'galaxy_s20', name: 'Galaxy S20' },
    { id: 'galaxy_s20_fe', name: 'Galaxy S20 FE' },
    { id: 'galaxy_note_20_ultra', name: 'Galaxy Note 20 Ultra' },
    { id: 'galaxy_note_20', name: 'Galaxy Note 20' },
    { id: 'galaxy_z_fold5', name: 'Galaxy Z Fold5' },
    { id: 'galaxy_z_flip5', name: 'Galaxy Z Flip5' },
    { id: 'galaxy_z_fold4', name: 'Galaxy Z Fold4' },
    { id: 'galaxy_z_flip4', name: 'Galaxy Z Flip4' },
    { id: 'galaxy_z_fold3', name: 'Galaxy Z Fold3' },
    { id: 'galaxy_z_flip3', name: 'Galaxy Z Flip3' },
    { id: 'galaxy_a55', name: 'Galaxy A55' },
    { id: 'galaxy_a35', name: 'Galaxy A35' },
    { id: 'galaxy_a15', name: 'Galaxy A15' },
    { id: 'galaxy_a73', name: 'Galaxy A73' },
    { id: 'galaxy_a53', name: 'Galaxy A53' },
    { id: 'galaxy_a33', name: 'Galaxy A33' },
    { id: 'galaxy_a23', name: 'Galaxy A23' },
    { id: 'galaxy_a13', name: 'Galaxy A13' },
    { id: 'galaxy_m55', name: 'Galaxy M55' },
    { id: 'galaxy_m34', name: 'Galaxy M34' },
    { id: 'galaxy_m53', name: 'Galaxy M53' },
    { id: 'galaxy_m33', name: 'Galaxy M33' },
    { id: 'galaxy_f54', name: 'Galaxy F54' },
    { id: 'galaxy_f23', name: 'Galaxy F23' },
  ],
  oppo: [
      { id: 'reno_11_pro', name: 'Reno 11 Pro' },
      { id: 'reno_11', name: 'Reno 11' },
      { id: 'reno_10_pro_plus', name: 'Reno 10 Pro+' },
      { id: 'reno_10_pro', name: 'Reno 10 Pro' },
      { id: 'reno_10', name: 'Reno 10' },
      { id: 'reno_8_pro', name: 'Reno 8 Pro' },
      { id: 'reno_8', name: 'Reno 8' },
      { id: 'reno_7_pro', name: 'Reno 7 Pro' },
      { id: 'reno_7', name: 'Reno 7' },
      { id: 'reno_6_pro', name: 'Reno 6 Pro' },
      { id: 'reno_6', name: 'Reno 6' },
      { id: 'find_n3_flip', name: 'Find N3 Flip' },
      { id: 'find_x5_pro', name: 'Find X5 Pro' },
      { id: 'find_x5', name: 'Find X5' },
      { id: 'f25_pro', name: 'F25 Pro' },
      { id: 'f23_pro', name: 'F23 Pro' },
      { id: 'f23', name: 'F23' },
      { id: 'f21_pro_plus', name: 'F21 Pro+' },
      { id: 'f21_pro', name: 'F21 Pro' },
      { id: 'a79', name: 'A79' },
      { id: 'a59', name: 'A59' },
      { id: 'a78', name: 'A78' },
      { id: 'a58', name: 'A58' },
      { id: 'a38', name: 'A38' },
      { id: 'k10', name: 'K10' },
  ],
  vivo: [
      { id: 'x100_pro', name: 'X100 Pro' },
      { id: 'x100', name: 'X100' },
      { id: 'x90_pro', name: 'X90 Pro' },
      { id: 'x90', name: 'X90' },
      { id: 'x80_pro', name: 'X80 Pro' },
      { id: 'x80', name: 'X80' },
      { id: 'v30_pro', name: 'V30 Pro' },
      { id: 'v30', name: 'V30' },
      { id: 'v29_pro', name: 'V29 Pro' },
      { id: 'v29', name: 'V29' },
      { id: 'v27_pro', name: 'V27 Pro' },
      { id: 'v27', name: 'V27' },
      { id: 't3', name: 'T3' },
      { id: 't2_pro', name: 'T2 Pro' },
      { id: 't2x', name: 'T2x' },
      { id: 't2', name: 'T2' },
      { id: 'y200e', name: 'Y200e' },
      { id: 'y28', name: 'Y28' },
      { id: 'y100', name: 'Y100' },
      { id: 'y56', name: 'Y56' },
      { id: 'y36', name: 'Y36' },
  ],
  redmi: [
      { id: 'note_13_pro_plus', name: 'Note 13 Pro+' },
      { id: 'note_13_pro', name: 'Note 13 Pro' },
      { id: 'note_13', name: 'Note 13' },
      { id: 'note_12_pro_plus', name: 'Note 12 Pro+' },
      { id: 'note_12_pro', name: 'Note 12 Pro' },
      { id: 'note_12', name: 'Note 12' },
      { id: 'note_11_pro_plus', name: 'Note 11 Pro+' },
      { id: 'note_11_pro', name: 'Note 11 Pro' },
      { id: 'note_11s', name: 'Note 11S' },
      { id: 'note_11t', name: 'Note 11T' },
      { id: 'note_11', name: 'Note 11' },
      { id: '13c', name: '13C' },
      { id: '12', name: '12' },
      { id: '12_pro', name: '12 Pro' },
      { id: '12c_2', name: '12C' },
      { id: '11_prime', name: '11 Prime' },
      { id: '10', name: '10' },
      { id: 'k50i', name: 'K50i' },
  ],
  realme: [
      { id: '12_pro_plus', name: '12 Pro+' },
      { id: '12_pro', name: '12 Pro' },
      { id: '12_plus', name: '12+' },
      { id: '11_pro_plus', name: '11 Pro+' },
      { id: '11_pro', name: '11 Pro' },
      { id: '11', name: '11' },
      { id: '10_pro_plus', name: '10 Pro+' },
      { id: '10_pro', name: '10 Pro' },
      { id: '10', name: '10' },
      { id: 'narzo_70_pro', name: 'Narzo 70 Pro' },
      { id: 'narzo_60_pro', name: 'Narzo 60 Pro' },
      { id: 'narzo_60', name: 'Narzo 60' },
      { id: 'narzo_50_pro', name: 'Narzo 50 Pro' },
      { id: 'narzo_50', name: 'Narzo 50' },
      { id: 'p1', name: 'P1' },
      { id: 'c67', name: 'C67' },
      { id: 'c55', name: 'C55' },
      { id: 'c53', name: 'C53' },
      { id: 'gt_2_pro', name: 'GT 2 Pro' },
      { id: 'gt_neo_3', name: 'GT Neo 3' },
      { id: 'gt_master_edition', name: 'GT Master Edition' },
  ],
  tecno: [
      { id: 'pova_6_pro', name: 'Pova 6 Pro' },
      { id: 'pova_5_pro', name: 'Pova 5 Pro' },
      { id: 'pova_5', name: 'Pova 5' },
      { id: 'spark_20c', name: 'Spark 20C' },
      { id: 'spark_20', name: 'Spark 20' },
      { id: 'spark_10_pro', name: 'Spark 10 Pro' },
      { id: 'spark_10', name: 'Spark 10' },
      { id: 'spark_go_2023', name: 'Spark Go 2023' },
      { id: 'phantom_v_fold', name: 'Phantom V Fold' },
      { id: 'phantom_v_flip', name: 'Phantom V Flip' },
      { id: 'camon_30_premier', name: 'Camon 30 Premier' },
      { id: 'camon_20_pro', name: 'Camon 20 Pro' },
      { id: 'camon_20', name: 'Camon 20' },
      { id: 'camon_19_pro', name: 'Camon 19 Pro' },
  ],
  iqoo: [
      { id: '12', name: '12' },
      { id: '11', name: '11' },
      { id: 'neo_9_pro', name: 'Neo 9 Pro' },
      { id: 'z9', name: 'Z9' },
      { id: 'z9x', name: 'Z9x' },
      { id: 'neo_7_pro', name: 'Neo 7 Pro' },
      { id: 'z7_pro', name: 'Z7 Pro' },
      { id: '9t', name: '9T' },
      { id: '9_pro', name: '9 Pro' },
      { id: '9', name: '9' },
      { id: 'z6_pro', name: 'Z6 Pro' },
      { id: 'z6_lite', name: 'Z6 Lite' },
  ],
  oneplus: [
    { id: 'oneplus_12', name: 'OnePlus 12' },
    { id: 'oneplus_12r', name: 'OnePlus 12R' },
    { id: 'oneplus_11', name: 'OnePlus 11' },
    { id: 'oneplus_11r', name: 'OnePlus 11R' },
    { id: 'oneplus_10_pro', name: 'OnePlus 10 Pro' },
    { id: 'oneplus_10r', name: 'OnePlus 10R' },
    { id: 'oneplus_10t', name: 'OnePlus 10T' },
    { id: 'oneplus_9_pro', name: 'OnePlus 9 Pro' },
    { id: 'oneplus_9', name: 'OnePlus 9' },
    { id: 'oneplus_9rt', name: 'OnePlus 9RT' },
    { id: 'oneplus_nord_ce4', name: 'OnePlus Nord CE 4' },
    { id: 'oneplus_nord_3', name: 'OnePlus Nord 3' },
    { id: 'oneplus_nord_2t', name: 'OnePlus Nord 2T' },
    { id: 'oneplus_nord_ce_2', name: 'OnePlus Nord CE 2' },
    { id: 'oneplus_nord_ce_2_lite', name: 'OnePlus Nord CE 2 Lite' },
    { id: 'oneplus_open', name: 'OnePlus Open' },
  ],
  google_pixel: [
      { id: 'pixel_8_pro', name: 'Pixel 8 Pro' },
      { id: 'pixel_8', name: 'Pixel 8' },
      { id: 'pixel_8a', name: 'Pixel 8a' },
      { id: 'pixel_fold', name: 'Pixel Fold' },
      { id: 'pixel_7_pro', name: 'Pixel 7 Pro' },
      { id: 'pixel_7', name: 'Pixel 7' },
      { id: 'pixel_7a', name: 'Pixel 7a' },
      { id: 'pixel_6_pro', name: 'Pixel 6 Pro' },
      { id: 'pixel_6', name: 'Pixel 6' },
      { id: 'pixel_6a', name: 'Pixel 6a' },
      { id: 'pixel_5', name: 'Pixel 5' },
      { id: 'pixel_5a', name: 'Pixel 5a' },
      { id: 'pixel_4a', name: 'Pixel 4a' },
  ],
  other: [],
};
